MLBF_SUPERVISED_TYPE: Classification
MLBF_LABEL_ID_COLUMNS: ID1
MLBF_LABEL_NAME_COLUMNS: NAME1
MLBF_DROP_COLUMNS: ['ID1']
MLBF_FEATURE_SELECTION_OPTION: ['voting', 'aggregate']
MLBF_N_FEATURE_TO_SELECT: 10