artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/classification/cnn_classifier/data_ingestion
  source_url: https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
  local_data_file: artifacts/classification/cnn_classifier/data_ingestion/cifar-100-python.tar.gz
  unzip_dir: artifacts/classification/cnn_classifier/data_ingestion
  trainset_file: cifar-100-python/train
  testset_file: cifar-100-python/test
  meta_file: cifar-100-python/meta
  metadata: artifacts/classification/cnn_classifier/data_ingestion/cifar100_trainset_info.csv

prepare_base_model:
  root_dir: artifacts/classification/cnn_classifier/prepare_base_model
  base_model_path: artifacts/classification/cnn_classifier/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/classification/cnn_classifier/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/classification/cnn_classifier/prepare_callbacks
  tensorboard_root_log_dir: artifacts/classification/cnn_classifier/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/classification/cnn_classifier/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/classification/cnn_classifier/training
  trained_model_path: artifacts/classification/cnn_classifier/training/model.h5

inference:
  root_dir: artifacts/classification/cnn_classifier/predict
  inference_model_path: artifacts/classification/cnn_classifier/predict/best_model.h5
  metadata: artifacts/classification/cnn_classifier/predict/cifar100_trainset_info.csv
